services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: tenpo_challenge_postgres
    environment:
      - 'POSTGRES_DB=history_db'
      - 'POSTGRES_USER=challenge_user'
      - 'POSTGRES_PASSWORD=EZh6QsAvNv0secfm16ArcBq9ikKCJC+G'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # espera a que la app esté lista.
      test: [ "CMD-SHELL", "pg_isready -U challenge_user -d history_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  challenge-api:
    build: . # Construye la imagen usando el Dockerfile en el directorio actual '.'
    container_name: tenpo_challenge_api
    ports:
      - "8080:8080"
    environment:
      # --- IMPORTANTE: Configuración para conectar a la BD DENTRO de Docker ---
      # Usamos el nombre del servicio 'postgres' como hostname, no 'localhost'
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/history_db
      SPRING_R2DBC_USERNAME: challenge_user
      SPRING_R2DBC_PASSWORD: EZh6QsAvNv0secfm16ArcBq9ikKCJC+G
      # Podrías añadir otros perfiles o variables si las necesitas:
    depends_on: # Hace que este servicio espere al servicio postgres
      postgres:
        condition: service_healthy # Espera hasta que el healthcheck de postgres pase

volumes:
  postgres_data: