server:
  port: 8080

spring:
  application:
    name: felipearrano-challenge-api
  data:
    redis:
      host: localhost
      port: 6379
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/history_db
    username: challenge_user
    password: EZh6QsAvNv0secfm16ArcBq9ikKCJC+G
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
  sql:
    init:
      mode: always

mock:
  percentage-service:
    percentage-value: 10.0
    delay: 500ms
    redis-key: "percentage:current"
    redis-ttl: 30m
    failure-rate: 0.5


resilience4j.retry:
  instances:
    percentageService:
      maxAttempts: 3
      waitDuration: 500ms
      retryExceptions:
        - java.lang.RuntimeException
        - java.util.concurrent.TimeoutException

resilience4j.circuitbreaker:
  instances:
    percentageService:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 2
      recordExceptions:
        - java.lang.RuntimeException
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  instances:
    apiGlobalLimiter:
      limitForPeriod: 3
      limitRefreshPeriod: 1m
      timeoutDuration: 50ms